HELP_BUTTON_TEXT = "Справка"
QUEUE_BUTTON_TEXT = "Очередь"
TAKE_NEXT_BUTTON_TEXT = "Взять из очереди"
STATS_BUTTON_TEXT = "Статистика"
CANCEL_BUTTON_TEXT = "Отменить"
OPERATORS_BUTTON_TEXT = "Команда"

USER_NAVIGATION_BUTTONS = frozenset({HELP_BUTTON_TEXT})
OPERATOR_NAVIGATION_BUTTONS = frozenset(
    {
        QUEUE_BUTTON_TEXT,
        TAKE_NEXT_BUTTON_TEXT,
        STATS_BUTTON_TEXT,
        CANCEL_BUTTON_TEXT,
    }
)
SUPER_ADMIN_NAVIGATION_BUTTONS = frozenset(
    {
        OPERATORS_BUTTON_TEXT,
    }
)
