HELP_BUTTON_TEXT = "Справка"
QUEUE_BUTTON_TEXT = "Очередь"
TAKE_NEXT_BUTTON_TEXT = "Взять следующую"
MY_TICKETS_BUTTON_TEXT = "Мои заявки"
STATS_BUTTON_TEXT = "Статистика"
CANCEL_BUTTON_TEXT = "Отмена"
BACK_BUTTON_TEXT = "Назад"
BACK_TO_TICKET_BUTTON_TEXT = "К заявке"
REFRESH_BUTTON_TEXT = "Обновить"
OPEN_BUTTON_TEXT = "Открыть"
CLOSE_BUTTON_TEXT = "Закрыть"
OPERATORS_BUTTON_TEXT = "Операторы"
MACROS_BUTTON_TEXT = "Макросы"
CATEGORIES_BUTTON_TEXT = "Темы"

USER_NAVIGATION_BUTTONS = frozenset({HELP_BUTTON_TEXT})
OPERATOR_NAVIGATION_BUTTONS = frozenset(
    {
        QUEUE_BUTTON_TEXT,
        TAKE_NEXT_BUTTON_TEXT,
        MY_TICKETS_BUTTON_TEXT,
        STATS_BUTTON_TEXT,
        CANCEL_BUTTON_TEXT,
    }
)
SUPER_ADMIN_NAVIGATION_BUTTONS = frozenset(
    {
        OPERATORS_BUTTON_TEXT,
        MACROS_BUTTON_TEXT,
        CATEGORIES_BUTTON_TEXT,
    }
)
ALL_NAVIGATION_BUTTONS = (
    USER_NAVIGATION_BUTTONS
    | OPERATOR_NAVIGATION_BUTTONS
    | SUPER_ADMIN_NAVIGATION_BUTTONS
)
